---
apiVersion: v1
kind: Service
metadata:
  name: kernel-universal
  labels:
    app: kernel-universal
spec:
  ports:
    - protocol: TCP
      name: kernel-shell-port
      port: 8080
      targetPort: 3000
    - protocol: TCP
      name: kernel-common-port
      port: 8081
      targetPort: 3001
  selector:
    app: kernel-universal
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dev-kv2-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    kubernetes.io/ingress.allow-http: 'true'
spec:
  rules:
    - host: kv2.dev.asimov.io
      http:
        paths:
          - path: /
            backend:
              serviceName: kernel-universal
              servicePort: 8080
          - path: /v1/graphql
            backend:
              serviceName: kernel-hasura
              servicePort: 8080
    - host: common.kv2.dev.asimov.io
      http:
        paths:
          - path: /
            backend:
              serviceName: kernel-universal
              servicePort: 8081
          - path: /v1/graphql
            backend:
              serviceName: kernel-hasura
              servicePort: 8080
  tls:
    - secretName: wildcard-asimov-io-tls
  backend:
    serviceName: kernel-universal
    servicePort: 80
