import React, { ReactNode } from 'react';
import { Story } from '@storybook/react';

export default {
  title: 'Example/SequenceViewer',
  loaders: [
    async (): Promise<ReactNode> => ({
      SequenceViewer: (await import('common/components/sequence-viewer'))
        .default,
    }),
  ],
  decorators: [
    (Component: Story): ReactNode => (
      <div style={{ height: '100vh', width: '100vw' }}>
        <Component />
      </div>
    ),
  ],
};

export const Linear: Story = (args, { loaded: { SequenceViewer } }) => {
  const options = {
    name: 'hEf1a',
    seq: 'TTGGCTCCGGTGCCCGTCAGTGGGCAGAGCGCACATCGCCCACAGTCCCCGAGAAGTTGgGGGGAGGGGTCGGCAATTGAACCGGTGCCTAGAGAAGGTGGCGCGGGGTAAACTGGGAAAGTGATGTCGTGTACTGGCTCCGCCTTTTTCCCGAGGGTGGGGGAGAACCGTATATAAGTGCAGTAGTCGCCGTGAACGTTCTTTTTCGCAACGGGTTTGCCGCCAGAACACAGGTAAGTGCCGTGTGTGGTTCCCGCGGGCCTGGCCTCTTTACGGGTTATGGCCCTTGCGTGCCTTGAATTACTTCCACCTGGCTGCAGTACGTGATTCTTGATCCCGAGCTTCGGGTTGGAAGTGGGTGGGAGAGTTCGtGGCCTTGCGCTTAAGGAGCCCCTTCGCCTCGTGCTTGAGTTGtGGCCTGGCCTGGGCGCTGGGGCCGCCGCGTGCGAATCTGGTGGCACCTTCGCGCCTGTCTCGCTGCTTTCGATAAGTCTCTAGCCATTTAAAATTTTTGATGACCTGCTGCGACGCTTTTTTTCTGGCAAGATAGTCTTGTAAATGCGGGCCAAGATCaGCACACTGGTATTTCGGTTTTTGGGGCCGCGGGCGGCGACGGGGCCCGTGCGTCCCAGCGCACATGTTCGGCGAGGCGGGGCCTGCGAGCGCGGCCACCGAGAATCGGACGGGGGTAGTCTCAAGCTGcCCGGCCTGCTCTGGTGCCTGGCCTCGCGCCGCCGTGTATCGCCCCGCCCTGGGCGGCAAGGCTGGCCCGGTCGGCACCAGTTGCGTGAGCGGAAAGATGGCCGCTTCCCGGCCCTGCTGCAGGGAGCaCAAAATGGAGGACGCGGCGCTCGGGAGAGCGGGCGGGTGAGTCACCCACACAAAGGAAAAGGGCCTTTCCGTCCTCAGCCGTCGCTTCATGTGACTCCACGGAGTACCGGGCGCCGTCCAGGCACCTCGATTAGTTCTCcAGCTTTTGGAGTACGTCGTCTTTAGGTTGGGGGGAGGGGTTTTATGCGATGGAGTTTCCCCACACTGAGTGGGTGGAGACTGAAGTTAGGCCAGCTTGGCACTTGATGTAATTCTCCTTGGAATTTGCCCTTTTTGAGTTTGGATCTTGGTTCATTCTCAAGCCTCAGACAGTGGTTCAAAGTTTTTTTCTTCCATTTCAGGTGTCGTga',
    viewer: 'linear',
    annotations: [
      { start: 0, end: 1181, name: 'hEf1a', direction: 1 },
      {
        start: 1181,
        end: 1231,
        name: "Synthetic 5'UTR 17",
        direction: 1,
      },
      {
        start: 1231,
        end: 2221,
        name: 'IGHG1',
        direction: 1,
      },
      {
        start: 2221,
        end: 2747,
        name: 'rb glob polyA',
        direction: 1,
      },
    ],
  };

  return (
    <SequenceViewer
      {...options}
      {...args}
      colors={[
        '#9DEAED', // cyan
        '#8FDE8C', // green
        '#CFF283', // light green
        '#8CDEBD', // teal
        '#F0A3CE', // pink
        '#F7C672', // orange
        '#F07F7F', // red
        '#FAA887', // red-orange
        '#F099F7', // magenta
        '#C59CFF', // purple
        '#6B81FF', // blue
        '#85A6FF', // light blue
      ]}
    />
  );
};

export const ConstructBoth: Story = (args, { loaded: { SequenceViewer } }) => {
  const options = {
    name: 'TU #1 (HC)',
    seq: 'TTGGCTCCGGTGCCCGTCAGTGGGCAGAGCGCACATCGCCCACAGTCCCCGAGAAGTTGgGGGGAGGGGTCGGCAATTGAACCGGTGCCTAGAGAAGGTGGCGCGGGGTAAACTGGGAAAGTGATGTCGTGTACTGGCTCCGCCTTTTTCCCGAGGGTGGGGGAGAACCGTATATAAGTGCAGTAGTCGCCGTGAACGTTCTTTTTCGCAACGGGTTTGCCGCCAGAACACAGGTAAGTGCCGTGTGTGGTTCCCGCGGGCCTGGCCTCTTTACGGGTTATGGCCCTTGCGTGCCTTGAATTACTTCCACCTGGCTGCAGTACGTGATTCTTGATCCCGAGCTTCGGGTTGGAAGTGGGTGGGAGAGTTCGtGGCCTTGCGCTTAAGGAGCCCCTTCGCCTCGTGCTTGAGTTGtGGCCTGGCCTGGGCGCTGGGGCCGCCGCGTGCGAATCTGGTGGCACCTTCGCGCCTGTCTCGCTGCTTTCGATAAGTCTCTAGCCATTTAAAATTTTTGATGACCTGCTGCGACGCTTTTTTTCTGGCAAGATAGTCTTGTAAATGCGGGCCAAGATCaGCACACTGGTATTTCGGTTTTTGGGGCCGCGGGCGGCGACGGGGCCCGTGCGTCCCAGCGCACATGTTCGGCGAGGCGGGGCCTGCGAGCGCGGCCACCGAGAATCGGACGGGGGTAGTCTCAAGCTGcCCGGCCTGCTCTGGTGCCTGGCCTCGCGCCGCCGTGTATCGCCCCGCCCTGGGCGGCAAGGCTGGCCCGGTCGGCACCAGTTGCGTGAGCGGAAAGATGGCCGCTTCCCGGCCCTGCTGCAGGGAGCaCAAAATGGAGGACGCGGCGCTCGGGAGAGCGGGCGGGTGAGTCACCCACACAAAGGAAAAGGGCCTTTCCGTCCTCAGCCGTCGCTTCATGTGACTCCACGGAGTACCGGGCGCCGTCCAGGCACCTCGATTAGTTCTCcAGCTTTTGGAGTACGTCGTCTTTAGGTTGGGGGGAGGGGTTTTATGCGATGGAGTTTCCCCACACTGAGTGGGTGGAGACTGAAGTTAGGCCAGCTTGGCACTTGATGTAATTCTCCTTGGAATTTGCCCTTTTTGAGTTTGGATCTTGGTTCATTCTCAAGCCTCAGACAGTGGTTCAAAGTTTTTTTCTTCCATTTCAGGTGTCGTgaGGGCGCTCGAGCAGGTTCAGAAGGAGATCAAAAACCCCCAAGGATCAAACgcgagcaccaaaggcccgagcgtgtttccgctggcgccgagcagcaaaagcaccagcggcggcaccgcggcgctgggctgcctggtgaaagattattttccggaaccggtgaccgtgagctggaacagcggcgcgctgaccagcggcgtgcatacctttccggcggtgctgcagagcagcggcctgtatagcctgagcagcgtggtgaccgtgccgagcagcagcctgggcacccagacctatatttgcaacgtgaaccataaaccgagcaacaccaaagtggataaaaaagtggaaccgaaaagctgcgataaaacccatacctgcccgccgtgcccggcgccggaactgctgggcggcccgagcgtgtttctgtttccgccgaaaccgaaagataccctgatgattagccgcaccccggaagtgacctgcgtggtggtggatgtgagccatgaagatccggaagtgaaatttaactggtatgtggatggcgtggaagtgcataacgcgaaaaccaaaccgcgcgaagaacagtataacagcacctatcgcgtggtgagcgtgctgaccgtgctgcatcaggattggctgaacggcaaagaatataaatgcaaagtgagcaacaaagcgctgccggcgccgattgaaaaaaccattagcaaagcgaaaggccagccgcgcgaaccgcaggtgtataccctgccgccgagccgcgatgaactgaccaaaaaccaggtgagcctgacctgcctggtgaaaggcttttatccgagcgatattgcggtggaatgggaaagcaacggccagccggaaaacaactataaaaccaccccgccggtgctggatagcgatggcagcttttttctgtatagcaaactgaccgtggataaaagccgctggcagcagggcaacgtgtttagctgcagcgtgatgcatgaagcgctgcataaccattatacccagaaaagcctgagcctgagcccgggcaaaTTCACTCCTCAGGTGCAGGCTGCCTATCAGAAGGTGGTGGCTGGTGTGGCCAATGCCCTGGCTCACAAATACCACTGAGATCTTTTTCCCTCTGCCAAAAATTATGGGGACATCATGAAGCCCCTTGAGCATCTGACTTCTGGCTAATAAAGGAAATTTATTTTCATTGCAATAGTGTGTTGGAATTTTTTGTGTCTCTCACTCGGAAGGACATATGGGAGGGCAAATCATTTAAAACATCAGAATGAGTATTTGGTTTAGAGTTTGGCAACATATGCCCATATGCTGGCTGCCATGAACAAAGGTTGGCTATAAAGAGGTCATCAGTATATGAAACAGCCCCCTGCTGTCCATTCCTTATTCCATAGAAAAGCCTTGACTTGAGGTTAGATTTTTTTTATATTTTGTTTTGTGTTATTTTTTTCTTTAACATCCCTAAAATTTTCCTTACATGTTTTACTAGCCAGATTTTTCCTCCTCTCCTGACTACTCCCAGTCATAGCTGTCCCTCTTCTCTTATGGAGAT',
    annotations: [
      { start: 0, end: 1181, name: 'hEf1a', direction: 1, color: '#fde5f2' },
      {
        start: 1181,
        end: 1231,
        name: "Synthetic 5'UTR 17",
        direction: 1,
        color: '#ebecff',
      },
      {
        start: 1231,
        end: 2221,
        name: 'IGHG1',
        direction: 1,
        color: '#FAA887',
      },
      {
        start: 2221,
        end: 2747,
        name: 'rb glob polyA',
        direction: 1,
        color: '#ffeee3',
      },
    ],
    translations: [{ start: 1231, end: 2221, name: 'cds', direction: 1 }],
    viewer: 'both',
  };

  return <SequenceViewer {...options} {...args} />;
};

export const ConstructCircular: Story = (
  args,
  { loaded: { SequenceViewer } }
) => {
  const options = {
    name: 'TU #1 (HC)',
    seq: 'TTGGCTCCGGTGCCCGTCAGTGGGCAGAGCGCACATCGCCCACAGTCCCCGAGAAGTTGgGGGGAGGGGTCGGCAATTGAACCGGTGCCTAGAGAAGGTGGCGCGGGGTAAACTGGGAAAGTGATGTCGTGTACTGGCTCCGCCTTTTTCCCGAGGGTGGGGGAGAACCGTATATAAGTGCAGTAGTCGCCGTGAACGTTCTTTTTCGCAACGGGTTTGCCGCCAGAACACAGGTAAGTGCCGTGTGTGGTTCCCGCGGGCCTGGCCTCTTTACGGGTTATGGCCCTTGCGTGCCTTGAATTACTTCCACCTGGCTGCAGTACGTGATTCTTGATCCCGAGCTTCGGGTTGGAAGTGGGTGGGAGAGTTCGtGGCCTTGCGCTTAAGGAGCCCCTTCGCCTCGTGCTTGAGTTGtGGCCTGGCCTGGGCGCTGGGGCCGCCGCGTGCGAATCTGGTGGCACCTTCGCGCCTGTCTCGCTGCTTTCGATAAGTCTCTAGCCATTTAAAATTTTTGATGACCTGCTGCGACGCTTTTTTTCTGGCAAGATAGTCTTGTAAATGCGGGCCAAGATCaGCACACTGGTATTTCGGTTTTTGGGGCCGCGGGCGGCGACGGGGCCCGTGCGTCCCAGCGCACATGTTCGGCGAGGCGGGGCCTGCGAGCGCGGCCACCGAGAATCGGACGGGGGTAGTCTCAAGCTGcCCGGCCTGCTCTGGTGCCTGGCCTCGCGCCGCCGTGTATCGCCCCGCCCTGGGCGGCAAGGCTGGCCCGGTCGGCACCAGTTGCGTGAGCGGAAAGATGGCCGCTTCCCGGCCCTGCTGCAGGGAGCaCAAAATGGAGGACGCGGCGCTCGGGAGAGCGGGCGGGTGAGTCACCCACACAAAGGAAAAGGGCCTTTCCGTCCTCAGCCGTCGCTTCATGTGACTCCACGGAGTACCGGGCGCCGTCCAGGCACCTCGATTAGTTCTCcAGCTTTTGGAGTACGTCGTCTTTAGGTTGGGGGGAGGGGTTTTATGCGATGGAGTTTCCCCACACTGAGTGGGTGGAGACTGAAGTTAGGCCAGCTTGGCACTTGATGTAATTCTCCTTGGAATTTGCCCTTTTTGAGTTTGGATCTTGGTTCATTCTCAAGCCTCAGACAGTGGTTCAAAGTTTTTTTCTTCCATTTCAGGTGTCGTgaGGGCGCTCGAGCAGGTTCAGAAGGAGATCAAAAACCCCCAAGGATCAAACgcgagcaccaaaggcccgagcgtgtttccgctggcgccgagcagcaaaagcaccagcggcggcaccgcggcgctgggctgcctggtgaaagattattttccggaaccggtgaccgtgagctggaacagcggcgcgctgaccagcggcgtgcatacctttccggcggtgctgcagagcagcggcctgtatagcctgagcagcgtggtgaccgtgccgagcagcagcctgggcacccagacctatatttgcaacgtgaaccataaaccgagcaacaccaaagtggataaaaaagtggaaccgaaaagctgcgataaaacccatacctgcccgccgtgcccggcgccggaactgctgggcggcccgagcgtgtttctgtttccgccgaaaccgaaagataccctgatgattagccgcaccccggaagtgacctgcgtggtggtggatgtgagccatgaagatccggaagtgaaatttaactggtatgtggatggcgtggaagtgcataacgcgaaaaccaaaccgcgcgaagaacagtataacagcacctatcgcgtggtgagcgtgctgaccgtgctgcatcaggattggctgaacggcaaagaatataaatgcaaagtgagcaacaaagcgctgccggcgccgattgaaaaaaccattagcaaagcgaaaggccagccgcgcgaaccgcaggtgtataccctgccgccgagccgcgatgaactgaccaaaaaccaggtgagcctgacctgcctggtgaaaggcttttatccgagcgatattgcggtggaatgggaaagcaacggccagccggaaaacaactataaaaccaccccgccggtgctggatagcgatggcagcttttttctgtatagcaaactgaccgtggataaaagccgctggcagcagggcaacgtgtttagctgcagcgtgatgcatgaagcgctgcataaccattatacccagaaaagcctgagcctgagcccgggcaaaTTCACTCCTCAGGTGCAGGCTGCCTATCAGAAGGTGGTGGCTGGTGTGGCCAATGCCCTGGCTCACAAATACCACTGAGATCTTTTTCCCTCTGCCAAAAATTATGGGGACATCATGAAGCCCCTTGAGCATCTGACTTCTGGCTAATAAAGGAAATTTATTTTCATTGCAATAGTGTGTTGGAATTTTTTGTGTCTCTCACTCGGAAGGACATATGGGAGGGCAAATCATTTAAAACATCAGAATGAGTATTTGGTTTAGAGTTTGGCAACATATGCCCATATGCTGGCTGCCATGAACAAAGGTTGGCTATAAAGAGGTCATCAGTATATGAAACAGCCCCCTGCTGTCCATTCCTTATTCCATAGAAAAGCCTTGACTTGAGGTTAGATTTTTTTTATATTTTGTTTTGTGTTATTTTTTTCTTTAACATCCCTAAAATTTTCCTTACATGTTTTACTAGCCAGATTTTTCCTCCTCTCCTGACTACTCCCAGTCATAGCTGTCCCTCTTCTCTTATGGAGAT',
    annotations: [
      { start: 0, end: 1181, name: 'hEf1a', direction: 1, color: '#fde5f2' },
      {
        start: 1181,
        end: 1231,
        name: "Synthetic 5'UTR 17",
        direction: 1,
        color: '#ebecff',
      },
      {
        start: 1231,
        end: 2221,
        name: 'IGHG1',
        direction: 1,
        color: '#FAA887',
      },
      {
        start: 2221,
        end: 2747,
        name: 'rb glob polyA',
        direction: 1,
        color: '#ffeee3',
      },
    ],
    translations: [{ start: 1231, end: 2221, name: 'cds', direction: 1 }],
    viewer: 'circular',
  };

  return <SequenceViewer {...options} {...args} />;
};
